### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by keirlawson** [mweirauch/metrics-jvm-extras#12]
When trying to use `FileDescriptorCountGauge` on JDK 11 I get the following:

```
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getOpenFileDescriptorCount() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @6f4e3135
```

**Comment by mweirauch** [comment]
Hi @keirlawson . Allthough I am not using the library anymore (I switched to Micrometer quite a while ago - see the sister project micrometer-jvm-extras), I am working on a fix. Might take a bit to get the maven deps including basepom to compile and test on Java11, so that I can enable the openjdk11 build in TravisCI.

**Comment by keirlawson** [comment]
Fantastic, thanks for fixing this so swiftly! Would it be possible to cut a release including this fix?

**Comment by mweirauch** [comment]
The [0.1.4 release](https://github.com/mweirauch/metrics-jvm-extras/releases/tag/0.1.4) is on its way to Maven Central, but the sync from Sonatype staging repos is said to take up to 2 hours. Have a look [here](http://repo1.maven.apache.org/maven2/io/github/mweirauch/metrics-jvm-extras/) from time to time.

Let me know if that works out for you.

**Comment by keirlawson** [comment]
That's perfect, cheers!

**Comment by keirlawson** [comment]
Hmmm it doesn't seem to have shown up at that link you posted

**Comment by mweirauch** [comment]
Yeah, also unsure if I clicked the right buttons, but closed the staging repo, then said release and then the repo "vanishes" (as it used to...). Will go digging a bit when time permits.

**Comment by mweirauch** [comment]
Seems like I am not the only one: https://issues.sonatype.org/browse/OSSRH-46959

**Comment by keirlawson** [comment]
Looks like its available now, have installed it in my project and seems to be working like a dream on JDK 11, thanks again for your prompt fix!

**Comment by mweirauch** [comment]
They likely had a hickup and a huge backlog. Glad that it works for you!
